### PR TITLE
Send function or paragraph

### PR DESCRIPTION
**Pull request by pimentel**
- Allow user to send function or paragraph
- Add configuration allowing notifications
- Add menu items allowing user to change destination application
- Add warning if file isn't saved and user calls `r-exec:setwd` (https://github.com/hafen/atom-r-exec/issues/18)

Would definitely appreciate a code review. Thanks!

### CODE REVIEW

**Comment by pimentel** [comment]
You're probably away on holiday, but I just wanted to ping : -)

Happy holidays!

**Comment by hafen** [comment]
Sorry for the delay - this is really great stuff!!  Thanks!  Actually, given that your contributions and momentum here far exceed what I've been able to contribute and will likely be able to contribute in the future, I was wondering if you would be interested in owning this repo.  Then you won't have to deal with me taking 20 days to review a PR :).  Let me know.

**Comment by pimentel** [comment]
@hafen no need to apologize! thanks for the response!

I'd be happy to take over the repo -- I've been using atom a lot and definitely see myself developing this package further (at least for mac). Thanks for all of your help with everything and for setting up this project.

**Comment by hafen** [comment]
Great thanks!  I'll merge and figure out how to transfer.

**Pull request merged**
